name: Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: flickpicker
  CONTAINER_APP_NAME: flickpicker
  RESOURCE_GROUP: FlickPicker
  STORAGE_ACCOUNT_NAME: flickpickerstorage
  STORAGE_CONTAINER_NAME: data-files
  MOUNT_PATH: /

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push container image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          file: Dockerfile

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve STORAGE_ACCOUNT_KEY from Key Vault
        run: |
          STORAGE_ACCOUNT_KEY=$(az keyvault secret show --vault-name flickpickerkeys --name storage-account-key --query value -o tsv)
          echo "STORAGE_ACCOUNT_KEY=$STORAGE_ACCOUNT_KEY" >> $GITHUB_ENV

      - name: Deploy to Azure Container Apps via CLI
        run: |
          # First, create or update the storage mount
          az containerapp env storage set \
            --name ${{ env.CONTAINER_APP_NAME }}-env \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --storage-name blobstorage \
            --azure-file-account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --azure-file-account-key ${{ env.STORAGE_ACCOUNT_KEY }} \
            --azure-file-share-name ${{ env.STORAGE_CONTAINER_NAME }} \
            --access-mode ReadWrite

          # Then update the container app with the storage mount and other settings
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
            --mount-type azure-file \
            --mount-name blobstorage \
            --mount-path ${{ env.MOUNT_PATH }} \
            --set-env-vars ASPNETCORE_ENVIRONMENT=Development \
              DJANGO_ADMIN_PASSWORD=${{ secrets.DJANGO_ADMIN_PASSWORD }} \
              GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              SECRET_KEY=${{ secrets.SECRET_KEY }} \
              TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} \
              OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              NOMIC_API_KEY=${{ secrets.NOMIC_API_KEY }} \
              PGDATABASE=${{ secrets.PGDATABASE }} \
              PGUSER=${{ secrets.PGUSER }} \
              PGPASSWORD=${{ secrets.PGPASSWORD }} \
              PGHOST=${{ secrets.PGHOST }} \
              PGPORT=${{ secrets.PGPORT }} \
              AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
              AZURE_STORAGE_CONTAINER_NAME=${{ env.STORAGE_CONTAINER_NAME }}
