# Generated by Django 5.1 on 2024-08-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmName', models.CharField(max_length=255)),
                ('filmGenre', models.CharField(max_length=255)),
            ],
        ),
    ]
