# Generated by Django 5.1 on 2024-08-20 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='filmGenre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='filmName',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(default='Unknown Director', max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(default='Unknown Genre', max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=100),
        ),
    ]
